sudo: false
language: java
jdk: openjdk11

env:
  - PRO_SPECIAL_BUILD='early-access'

cache:
  directories:
    # Pro
    - $HOME/deps

install:
  - java pro_wrapper.java version

script:
  - ./pro/bin/pro

